### ISSUE TITLE
Problems with Kibana Helmfile

### ISSUE THREAD

**Issue by osterman** [cloudposse/helmfiles#11]
## what

```
2018/08/04 00:48:13 err: failed to read helmfile.d/0630.kibana.yaml: yaml: line 76: mapping values are not allowed in this context
```

## why

This will only render correctly if envs are set. Helmfile always renders all templates first as text, then as yaml. Thus, the resultant yaml is invalid because we basically have

```
elasticsearch.url: :
```

Let's make sure to always quote strings where strings are expected.

```
     kibana.yml:
        ## Default Kibana configuration from kibana-docker.
        server.name: kibana
        server.host: "localhost"
        elasticsearch.url: {{ env "ELASTICSEARCH_HOST" }}:{{ env "ELASTICSEARCH_PORT" }}

        ## Custom config properties
        ## Ref: https://www.elastic.co/guide/en/kibana/current/settings.html
        server.port: {{ env "KIBANA_SERVER_PORT" | default "5601" }}
        logging.verbose: "false"
        server.defaultRoute: "/app/kibana"
```

Also, the `ELASTICSEARCH_URL` and `SERVER_PORT` are not correctly indented.
